### ISSUE TITLE
Support for /db/_find

### ISSUE THREAD

**Issue by andreassiegel** [redgeoff/slouch#101]
Right now, slouch doesn't seem to provide support for document retrieval using the `POST /{db}/_find` endpoint in the CouchDB API (see https://docs.couchdb.org/en/latest/api/database/find.html) or something similar.

It would be good if the ability to find documents based on some queries instead of just the ID could be added.

**Comment by redgeoff** [comment]
I agree! Would you be willing to create a PR?

**Comment by redgeoff** [comment]
Implemented by https://github.com/redgeoff/slouch/pull/102
