### ISSUE TITLE
First 8 charcters of view id is escaped

### ISSUE THREAD

**Issue by dinanjana** [redgeoff/slouch#104]
Why are we leaving first 8 characters of view id when calling a couchdb view in here? 
https://github.com/redgeoff/slouch/blob/239272acd849dd90fe563cd6f6b54d94bcbc6d15/scripts/db.js#L120

**Comment by redgeoff** [comment]
The viewDocId is the id of the doc, which includes __design_. That being said, CouchDB expects all characters after the __design/_ to be URI encoded.
