### ISSUE TITLE
Different approach for sending request body at create and update doc methods

### ISSUE THREAD

**Issue by jovanmilenkoski** [redgeoff/slouch#107]
![image](https://user-images.githubusercontent.com/32868801/53288079-b8f84580-3784-11e9-801d-7e9f62314a5b.png)

Encountered an error using mock-couch as db server. The request body was missing, so I dig deeper and found out that you are using different body sending parameters. 

CREATE uses "json: doc", UPDATE uses "JSON.stringify(doc), paraseBody: true" 
check the image

When I "hack" the UPDATE method and send "json: doc", everything looks okay.

What are your thoughts on this?

**Comment by redgeoff** [comment]
I actually don't remember why I choose to use both, but I'd suspect that there is a reason. I'd suggest creating a PR where you replace all occurrences of parseBody and see if the automated tests pass.
