### ISSUE TITLE
How do I do cookie authentication?

### ISSUE THREAD

**Issue by standup75** [redgeoff/slouch#26]
I am trying to implement one-database-per-user with a service on my express app using slouch, it looks like that:

    const Slouch = require('couch-slouch')
    const config = require('./config')

    const slouch = new Slouch(config.couchDb.url)

    module.exports = {
      createDb(user) {
        const dbName = `${config.couchDbBaseName}_${user.email}`
        return slouch.user.createSession({
          username: config.couchDb.username,
          password: config.couchDb.password
        })
        .then(response => slouch.user.create(user.email, user.dbpwd))
        .then(response => slouch.db.create(dbName))
        .then(response => slouch.security.set(dbName, {
            admins: { names: [], roles: [] },
            members: { names: [user.email], roles: [] }
          })
        )
      }
    }

I was hoping some magic would happen and the cookie from the createSession response would be sent with the next commands. But although the user creation works (maybe my db lets anyone create users? oops), the following slouch.db.create call is failing with 'unauthorized'. If there a way to get through this?

**Comment by redgeoff** [comment]
Yeah, cookie authentication in this manner isn't something that we've needed to do yet so it is missing. I just took a few minutes to get something working and got it mostly working, but I need to make some changes downstream to finish it off. I'll post here when the changes are ready.

**Comment by redgeoff** [comment]
Here is a WIP that adds cookie authentication support in node: https://github.com/redgeoff/slouch/pull/27. I'll finish this up shortly.

Cookie authentication support for the browser cannot be added until https://github.com/redgeoff/slouch/issues/10 is completed

**Comment by standup75** [comment]
Awesome, thanks. I just had a quick look at it. I have something working with nano. But it looks ugly (transform callback into promise all the things), so I'll give it a shot on Monday. Slouch is really neat and so was your article on creating couchDB instance on AWS. Kind of hooked to couchDB this week...

**Comment by redgeoff** [comment]
Cool!

https://github.com/redgeoff/slouch/pull/27 was merged and is part of 0.1.0 on npm.

See [Authentication Example](https://github.com/redgeoff/slouch/blob/master/examples/authentication.js) for an example

**Comment by standup75** [comment]
This is working perfectly. I have a small couchDB question, it seems counter-intuitive to me to put the user in the role field using the method onlyRoleCanView, shouldn't there be a method onlyUserCanView that set the names field of the _security document?

**Comment by redgeoff** [comment]
Sure, `onlyUserCanView` would be a great addition to the Slouch API. Interested in submitting a PR?
