### ISSUE TITLE
Set cookie whenever request has Set-Cookie header

### ISSUE THREAD

**Issue by redgeoff** [redgeoff/slouch#44]
As per https://stackoverflow.com/a/10359837/2831606, if we are not using persistent cookies (`allow_persistent_cookies`=false) then CouchDB can change/refresh our cookie during any request. If this happens, we should update the locally stored cookie. The code to set the cookie would look something like [this](https://github.com/redgeoff/slouch/blob/54a60e7a214881b5254cacfdde817391adf962e6/scripts/user.js#L216)

**Comment by layanto** [comment]
I can access set-cookie header in the response in EnhancedRequest.prototype._request but not sure how to access RequestWrapper.prototype.setCookie from there.

**Comment by layanto** [comment]
Figured this out. Will raise PR.
