### ISSUE TITLE
Add equivalent to `nano.db.list`

### ISSUE THREAD

**Issue by thomastoye** [redgeoff/slouch#88]
As it stands, there's no facility for listing all databases on a CouchDB server in `slouch`.

**Comment by thomastoye** [comment]
Took a peek at the code, seems like something like this would work:

```
DB.prototype.listDatabases = function () {
  return this._slouch._req({
    uri: this._slouch._url + '/_all_dbs',
    method: 'GET'
  });
};
```

**Comment by redgeoff** [comment]
Thanks, but this functionality already exists at slouch.db.all() and it is more scalable as it uses a StreamIterator, e.g.

```js
slouch.db.all().each(function (db) {

  // for each db

}).then(function () {

  // Done iterating through all docs

}).catch (function (err) {

  // An error occurred

});
```
